# Generated by Django 6.0.4 on 2026-05-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioitem",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Portfolio rasmi. Maksimal 10 MB. Avtomatik siqiladi.",
                null=True,
                upload_to="portfolio/",
            ),
        ),
    ]
