# Generated by Django 6.0.4 on 2026-05-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="currency",
            field=models.CharField(
                choices=[("UZS", "so'm"), ("USD", "USD")], default="UZS", max_length=3
            ),
        ),
    ]
