# Generated by Django 6.0.4 on 2026-05-24 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refresh_jti",
                    models.CharField(
                        help_text="Refresh tokenning JTI claim qiymati. Token rotatsiyasida yangilanadi.",
                        max_length=255,
                        unique=True,
                        verbose_name="JWT Token ID",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        default="Noma'lum qurilma",
                        help_text="Masalan: iPhone / Safari, Android / Chrome, Windows / Edge",
                        max_length=255,
                        verbose_name="Qurilma nomi",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP manzil"
                    ),
                ),
                (
                    "last_active",
                    models.DateTimeField(auto_now=True, verbose_name="Oxirgi faollik"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qurilma Sessiyasi",
                "verbose_name_plural": "Qurilma Sessiyalari",
                "ordering": ["-last_active"],
            },
        ),
    ]
